### ISSUE TITLE
Duplicated data in decompressed file

### ISSUE THREAD

**Issue by eberzosa** [jamestelfer/Blast#2]
This happens due to an issue in the window sliding and the copy function

1. _outputBuffer = xxxxxxxxxxz (x: 8000 used byes, z: 96 unused bytes)
2. _outputBufferPos = 8000
3. EnsureBufferSpace(100) is called from CopyBufferSection
    3a. startWindowOffset = 8000 - 4096 = 3904
    3b. Copy -> yyyyyxxxxz (y: 4096 bytes moved from startWindowOffset to 0, rest: old data)
    3c. _outputBufferPos = 4096
4. CopyBufferSection continues
    4a. fromIndex = 4000
    4b. Copy -> From 4000 which is already wrong as the old data at 4000 before calling the EnsureBufferSpace is not longer there as it was overwritten by 3b

**Comment by jamestelfer** [comment]
Fixed in #3, now merged.
